import { Router } from "express";
import "../../container";
import { container } from "tsyringe";
import { ProductsController } from "./products.controller";
import { requireAdminAuth, requireAdminRole } from "../../middlewares/admin-auth.middleware";
import { dtoValidation } from "../../middlewares/dtoValidation";
import { ProductDto, PartDto, InventoryAdjustDto } from "./products.dto";
import { Role } from "../../generated/prisma/enums";
const r = Router(), c = container.resolve(ProductsController);
r.get("/products", c.products);
r.get("/parts", c.parts);
r.use("/admin", requireAdminAuth, requireAdminRole(Role.ADMIN, Role.SADMIN));
r.post("/admin/products", dtoValidation(ProductDto), c.createProduct);
r.patch("/admin/products/:id", dtoValidation(ProductDto), c.updateProduct);
r.post("/admin/parts", dtoValidation(PartDto), c.createPart);
r.patch("/admin/parts/:id", dtoValidation(PartDto), c.updatePart);
r.get("/admin/inventory", c.inventory);
r.patch("/admin/inventory/:id", dtoValidation(InventoryAdjustDto), c.adjust);
export default r;
