import {injectable} from "tsyringe";import createHttpError from "http-errors";import prisma from "../../config/database";
@injectable() export class ProductsService{
 async products(page=1,limit=20){const [data,total]=await Promise.all([prisma.product.findMany({where:{isActive:true},skip:(page-1)*limit,take:limit,orderBy:{createdAt:"desc"},include:{inventory:true}}),prisma.product.count({where:{isActive:true}})]);return {data,pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}};}
 createProduct(data:any){return prisma.product.create({data});} updateProduct(id:string,data:any){return prisma.product.update({where:{id},data});}
 async parts(page=1,limit=20){const [data,total]=await Promise.all([prisma.part.findMany({where:{isActive:true},skip:(page-1)*limit,take:limit,orderBy:{createdAt:"desc"},include:{inventory:true}}),prisma.part.count({where:{isActive:true}})]);return {data,pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}};}
 createPart(data:any){return prisma.part.create({data});} updatePart(id:string,data:any){return prisma.part.update({where:{id},data});}
 async inventory(){return prisma.inventory.findMany({include:{product:true,part:true,branch:true},orderBy:{updatedAt:"desc"}});}
 async adjust(inventoryId:string,quantity:number,note?:string){return prisma.$transaction(async tx=>{const inv=await tx.inventory.findUnique({where:{id:inventoryId}});if(!inv)throw createHttpError(404,"Inventory not found.");const next=inv.quantity+quantity;if(next<0)throw createHttpError(400,"Insufficient inventory.");const updated=await tx.inventory.update({where:{id:inventoryId},data:{quantity:next}});await tx.inventoryTransaction.create({data:{inventoryId,type:quantity>=0?"IN":"OUT",quantity:Math.abs(quantity),note}});return updated;});}
 async purchase(vendorId:string,type:"PRODUCT"|"PART",itemId:string,quantity:number){if(quantity<1)throw createHttpError(400,"Quantity must be positive.");return prisma.$transaction(async tx=>{const item=type==="PRODUCT"?await tx.product.findUnique({where:{id:itemId}}):await tx.part.findUnique({where:{id:itemId}});if(!item||!item.isActive)throw createHttpError(404,"Item not found.");if(item.stock<quantity)throw createHttpError(400,"Insufficient stock.");const total=Number(item.price)*quantity;const wallet=await tx.wallet.findUnique({where:{vendorId}});if(!wallet||Number(wallet.balance)<total)throw createHttpError(400,"Insufficient wallet balance.");const next=wallet.balance.minus(total);await tx.wallet.update({where:{id:wallet.id},data:{balance:next,totalSpent:wallet.totalSpent.plus(total)}});if(type==="PRODUCT")await tx.product.update({where:{id:itemId},data:{stock:{decrement:quantity}}});else await tx.part.update({where:{id:itemId},data:{stock:{decrement:quantity}}});const txn=await tx.walletTransaction.create({data:{walletId:wallet.id,type:type==="PRODUCT"?"PRODUCT_PURCHASE":"PART_PURCHASE",status:"SUCCESS",amount:total,balanceAfter:next,referenceId:itemId,note:`${type} purchase x${quantity}`}});return {total,transaction:txn};});}
}
